name: Generate Profile Cards

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output

      - name: Generate language cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: loczek7
          THEME: tokyonight
