name: Generate Profile Cards

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate language cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: loczek7
          theme: tokyonight
